Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 3479
"GET /swagger HTTP/1.1" 301 0
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/swagger-ui.html
"GET /swagger/ HTTP/1.1" 500 112542
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3530
"GET /redoc HTTP/1.1" 301 0
Internal Server Error: /redoc/
Traceback (most recent call last):
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/redoc.html
"GET /redoc/ HTTP/1.1" 500 110358
Watching for file changes with StatReloader
Internal Server Error: /redoc/
Traceback (most recent call last):
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/redoc.html
"GET /redoc/ HTTP/1.1" 500 110495
"GET /swagger HTTP/1.1" 301 0
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\drf_yasg\renderers.py", line 79, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg/swagger-ui.html
"GET /swagger/ HTTP/1.1" 500 112542
Watching for file changes with StatReloader
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\renderers.py", line 160, in render
    template = self.resolve_template(template_names)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf_spectacular/swagger_ui.html
"GET /swagger/ HTTP/1.1" 500 108753
Watching for file changes with StatReloader
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\renderers.py", line 160, in render
    template = self.resolve_template(template_names)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf_spectacular/swagger_ui.html
"GET /swagger/ HTTP/1.1" 500 108753
Watching for file changes with StatReloader
Internal Server Error: /api/auth/register
Traceback (most recent call last):
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
    ...<9 lines>...
    )
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/auth/register/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
"POST /api/auth/register HTTP/1.1" 500 89611
"GET /api/auth/register HTTP/1.1" 301 0
Internal Server Error: /api/auth/register/
Traceback (most recent call last):
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django_redis\cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django_redis\cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django_redis\client\default.py", line 300, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\views.py", line 422, in initial
    self.check_throttles(request)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\views.py", line 365, in check_throttles
    if not throttle.allow_request(request, self):
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\throttling.py", line 123, in allow_request
    self.history = self.cache.get(self.key, [])
                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django_redis\cache.py", line 92, in get
    value = self._get(key, default, version, client)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django_redis\cache.py", line 36, in _decorator
    raise e.__cause__  # noqa: B904
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django_redis\client\default.py", line 298, in get
    value = client.get(key)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\redis\commands\core.py", line 1822, in get
    return self.execute_command("GET", name, keys=[name])
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\redis\client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\redis\client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\redis\connection.py", line 1423, in get_connection
    connection.connect()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\redis\connection.py", line 364, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.
"GET /api/auth/register/ HTTP/1.1" 500 171238
Internal Server Error: /redoc/
Traceback (most recent call last):
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\renderers.py", line 160, in render
    template = self.resolve_template(template_names)
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\rest_framework\renderers.py", line 170, in resolve_template
    return loader.select_template(template_names)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\jeffe\Downloads\projects\fincart\backend\core\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf_spectacular/redoc.html
"GET /redoc/ HTTP/1.1" 500 107855
